more space debugging

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -19,22 +19,25 @@ cd $CHROME_DIR
 REV=775629
 wget -q -O chrome.zip https://commondatastorage.googleapis.com/chromium-browser-snapshots/Linux_x64/$REV/chrome-linux.zip \
   && unzip chrome.zip \
-  && rm chrome.zip \
+  && rm chrome.zip
+echo "-----> Sizes:"
+ls -lhaSr
+ls -lhaSr locales
 
 echo "-----> Check chromium-linux version"
-$CHROME_DIR/chrome-linux/chrome --version  && echo "-----> Chromium browser installed!" || echo "-----> Chromium browser Failed!"
+$CHROME_DIR/chrome-linux/chrome --version  && echo "-----> Chromium browser OK!" || echo "-----> Chromium browser Error!"
 
-echo "-----> Folder occupation in CHROME_DIR:"
-cd $CHROME_DIR
-du -h $(ls -A) | sort -h
+# echo "-----> Folder occupation in CHROME_DIR:"
+# cd $CHROME_DIR
+# du -h $(ls -A) | sort -h
 
-echo "-----> Folder occupation in BUILD_DIR:"
-cd $BUILD_DIR
-du -h $(ls -A) | sort -h
+# echo "-----> Folder occupation in BUILD_DIR:"
+# cd $BUILD_DIR
+# du -h $(ls -A) | sort -h
 
-echo "-----> Folder occupation in CACHE_DIR:"
-cd $CACHE_DIR
-du -h $(ls -A) | sort -h
+# echo "-----> Folder occupation in CACHE_DIR:"
+# cd $CACHE_DIR
+# du -h $(ls -A) | sort -h
 
 # ln -s $PWD/chrome-linux/chrome /usr/bin/google-chrome-unstable
 # cp start.sh /usr/bin/
